bvnmEM <- function(x, max.iter=100, tol=0.00001){
	#input is a matrix and control parameters
	n <- dim(x)[1]
	p <- dim(x)[2]
	#identify missingness
	naind <- !is.na(x)
	
	#find complete data (i.e. data where there is no missingness; used to generate starting values)
	compind <- naind[,1]
	for(i in 2:p){
		compind <- compind & naind[,i]
	}
	complete <- x[compind,]
	
	#define regression pars, coefficients and the residual variances
	betas <- matrix(0, nrow=p,  ncol=p)
	resvar <- numeric(p)
	
	#starting values are generated by the regression of x1 on x2, and x2 on x1
	for(i in 1:p) betas[,i] <- lm(complete[,i] ~ complete[,-i])$coef
	datak <- x
	#impute missing values with predicted values
	for(i in 1:p){
		for(j in 1:n){
			if(!naind[j,i])	datak[j, i] <-   c(1, datak[j, -i]) %*% betas[,i]
		}
	}

	#sufficient statistics
	s1 <- numeric(1)
	s2 <- numeric(1)
	s11 <- numeric(1)
	s22 <- numeric(1)
	s12 <- numeric(1)
	
	oldpar <- numeric(5)

	for(k in 1:max.iter){
		#repeat procedure up to max.iter times
		for(i in 1:p){
			regr <- glm(datak[,i] ~ datak[,-i])
			betas[,i] <- regr$coefficients
			resvar[i] <- sum(regr$residuals^2)/(n-p)
			for(j in 1:n){
				if(!naind[j,i])	datak[j, i] <-   c(1, datak[j, -i]) %*% betas[,i]
			}
		}
		oldpar <- c(s1, s2, s11/n-(s1/n)^2, s22/n-(s2/n)^2, s12/n - (s2/n) * (s1/n))
		s1 <- sum(datak[,1])
		s2 <- sum(datak[,2])
		s11 <- sum(datak[,1]^2) + sum(!naind[,1]) * resvar[1]
		s22 <- sum(datak[,2]^2) + sum(!naind[,2]) * resvar[2]
		s12 <- sum(datak[,1] * datak[,2])
		#if any of the differences are larger than tol, keep going, else break loop
		if( !any((abs(c(s1, s2, s11/n-(s1/n)^2, s22/n-(s2/n)^2, s12/n - (s2/n) * (s1/n)))-abs(oldpar)) > tol) ) break
	}
	#return estimated mean vector and covariance matrix, along with no of iterations
	return(list(mean=c(s1,s2)/n, cov=matrix(c(s11/n-(s1/n)^2, s12/n - (s2/n) * (s1/n), s12/n - (s2/n) * (s1/n), s22/n-(s2/n)^2), nrow=2), iterations=k) )	
}

#does it work correctly? (not entirely sure!)
#generalize multivariate case?
#not efficient code! (at all)

bvmat <- matrix(c( c(8, NA, NA, 18, 6, 4, NA, 25, 9, 13), c(10, 14, 16, 15, 20, 4, 18, 22, NA, NA)), ncol=2)

bvnmEM(bvmat, tol=0.00001)
